version: '3.7'

services:
  ofs_pgsql:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - ofs_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '${DEFAULT_DATABASE_PORT}:5432'
  ofs_nuxt:
    restart: unless-stopped
    image: ghcr.io/selfagency/openformstack:latest
    environment: DEFAULT_DATABASE_HOSTNAME=${DEFAULT_DATABASE_HOSTNAME}
      DEFAULT_DATABASE_USER=${DEFAULT_DATABASE_USER}
      DEFAULT_DATABASE_PASSWORD=${DEFAULT_DATABASE_PASSWORD}
      DEFAULT_DATABASE_PORT=${DEFAULT_DATABASE_PORT}
      DEFAULT_DATABASE_DB=${DEFAULT_DATABASE_DB}
      DATABASE_URL=${DATABASE_URL}
      GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      API_ROUTE_SECRET=${API_ROUTE_SECRET}
      RESEND_API_KEY=${RESEND_API_KEY}
      FROM_MAIL=${FROM_MAIL}
      BASE_URL=${BASE_URL}

volumes:
  ofs_data:
